[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "axher-ai"
version = "0.1.0"
description = "AI services for Axher"
requires-python = ">=3.14"

dependencies = [
    "fastapi[standard]",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]